# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preface',
            field=models.TextField(blank=True, null=True),
        ),
    ]
